/* config.h.  Generated by configure.  */
/* config.h.in.  Generated from configure.in by autoheader.  */
#define HANZI 1
#define NARROWPROTO 1

/* Define to 1 if the `getpgrp' function requires zero arguments. */
#define GETPGRP_VOID 1

/* Define to 1 if you have the <dirent.h> header file, and it defines `DIR'.
   */
#define HAVE_DIRENT_H 1

/* Define to 1 if you have the `gettimeofday' function. */
#define HAVE_GETTIMEOFDAY 1

/* Define to 1 if you have the <inttypes.h> header file. */
#define HAVE_INTTYPES_H 1

/* Define to 1 if you have the `dps' library (-ldps). */
/* #undef HAVE_LIBDPS */

/* Define to 1 if you have the `dpstk' library (-ldpstk). */
/* #undef HAVE_LIBDPSTK */

/* Define to 1 if you have the `fl' library (-lfl). */
/* #undef HAVE_LIBFL */

/* Define to 1 if you have the `fntstubs' library (-lfntstubs). */
/* #undef HAVE_LIBFNTSTUBS */

/* Define to 1 if you have the `freetype' library (-lfreetype). */
#define HAVE_LIBFREETYPE 1

/* Define to 1 if you have the `FS' library (-lFS). */
/* #undef HAVE_LIBFS */

/* Define to 1 if you have the `GL' library (-lGL). */
#define HAVE_LIBGL 1

/* Define to 1 if you have the `GLU' library (-lGLU). */
/* #undef HAVE_LIBGLU */

/* Define to 1 if you have the `GLw' library (-lGLw). */
/* #undef HAVE_LIBGLW */

/* Define to 1 if you have the `ICE' library (-lICE). */
#define HAVE_LIBICE 1

/* Define to 1 if you have the `ncurses' library (-lncurses). */
#define HAVE_LIBNCURSES 1

/* Define to 1 if you have the `oldX' library (-loldX). */
/* #undef HAVE_LIBOLDX */

/* Define to 1 if you have the `PEX5' library (-lPEX5). */
/* #undef HAVE_LIBPEX5 */

/* Define to 1 if you have the `phigs' library (-lphigs). */
/* #undef HAVE_LIBPHIGS */

/* Define to 1 if you have the `psres' library (-lpsres). */
/* #undef HAVE_LIBPSRES */

/* Define to 1 if you have the `SM' library (-lSM). */
#define HAVE_LIBSM 1

/* Define to 1 if you have the `X11' library (-lX11). */
#define HAVE_LIBX11 1

/* Define to 1 if you have the `Xa' library (-lXa). */
/* #undef HAVE_LIBXA */

/* Define to 1 if you have the `Xau' library (-lXau). */
#define HAVE_LIBXAU 1

/* Define to 1 if you have the `Xaw' library (-lXaw). */
#define HAVE_LIBXAW 1

/* Define to 1 if you have the `Xbsd' library (-lXbsd). */
/* #undef HAVE_LIBXBSD */

/* Define to 1 if you have the `Xdmcp' library (-lXdmcp). */
#define HAVE_LIBXDMCP 1

/* Define to 1 if you have the `Xext' library (-lXext). */
#define HAVE_LIBXEXT 1

/* Define to 1 if you have the `Xfont' library (-lXfont). */
/* #undef HAVE_LIBXFONT */

/* Define to 1 if you have the `Xfontcache' library (-lXfontcache). */
/* #undef HAVE_LIBXFONTCACHE */

/* Define to 1 if you have the `Xft' library (-lXft). */
#define HAVE_LIBXFT 1

/* Define to 1 if you have the `Xi' library (-lXi). */
#define HAVE_LIBXI 1

/* Define to 1 if you have the `XIE' library (-lXIE). */
/* #undef HAVE_LIBXIE */

/* Define to 1 if you have the `Xinerama' library (-lXinerama). */
#define HAVE_LIBXINERAMA 1

/* Define to 1 if you have the `xkbfile' library (-lxkbfile). */
/* #undef HAVE_LIBXKBFILE */

/* Define to 1 if you have the `xkbui' library (-lxkbui). */
/* #undef HAVE_LIBXKBUI */

/* Define to 1 if you have the `Xkey' library (-lXkey). */
/* #undef HAVE_LIBXKEY */

/* Define to 1 if you have the `Xmu' library (-lXmu). */
#define HAVE_LIBXMU 1

/* Define to 1 if you have the `Xmuu' library (-lXmuu). */
/* #undef HAVE_LIBXMUU */

/* Define to 1 if you have the `Xp' library (-lXp). */
/* #undef HAVE_LIBXP */

/* Define to 1 if you have the `Xpm' library (-lXpm). */
#define HAVE_LIBXPM 1

/* Define to 1 if you have the `Xrender' library (-lXrender). */
#define HAVE_LIBXRENDER 1

/* Define to 1 if you have the `Xss' library (-lXss). */
/* #undef HAVE_LIBXSS */

/* Define to 1 if you have the `Xt' library (-lXt). */
#define HAVE_LIBXT 1

/* Define to 1 if you have the `Xtst' library (-lXtst). */
#define HAVE_LIBXTST 1

/* Define to 1 if you have the `Xv' library (-lXv). */
/* #undef HAVE_LIBXV */

/* Define to 1 if you have the `Xxf86dga' library (-lXxf86dga). */
/* #undef HAVE_LIBXXF86DGA */

/* Define to 1 if you have the `Xxf86misc' library (-lXxf86misc). */
/* #undef HAVE_LIBXXF86MISC */

/* Define to 1 if you have the `Xxf86rush' library (-lXxf86rush). */
/* #undef HAVE_LIBXXF86RUSH */

/* Define to 1 if you have the `Xxf86vm' library (-lXxf86vm). */
#define HAVE_LIBXXF86VM 1

/* Define to 1 if you have the <memory.h> header file. */
#define HAVE_MEMORY_H 1

/* Define to 1 if you have the <ndir.h> header file, and it defines `DIR'. */
/* #undef HAVE_NDIR_H */

/* Define to 1 if you have the `select' function. */
#define HAVE_SELECT 1

/* Define to 1 if you have the <sgtty.h> header file. */
#define HAVE_SGTTY_H 1

/* Define to 1 if you have the <stdint.h> header file. */
#define HAVE_STDINT_H 1

/* Define to 1 if you have the <stdlib.h> header file. */
#define HAVE_STDLIB_H 1

/* Define to 1 if you have the `strerror' function. */
#define HAVE_STRERROR 1

/* Define to 1 if you have the <strings.h> header file. */
#define HAVE_STRINGS_H 1

/* Define to 1 if you have the <string.h> header file. */
#define HAVE_STRING_H 1

/* Define to 1 if `st_rdev' is member of `struct stat'. */
#define HAVE_STRUCT_STAT_ST_RDEV 1

/* Define to 1 if your `struct stat' has `st_rdev'. Deprecated, use
   `HAVE_STRUCT_STAT_ST_RDEV' instead. */
#define HAVE_ST_RDEV 1

/* Define to 1 if you have the <sys/dir.h> header file, and it defines `DIR'.
   */
/* #undef HAVE_SYS_DIR_H */

/* Define to 1 if you have the <sys/ioctl.h> header file. */
#define HAVE_SYS_IOCTL_H 1

/* Define to 1 if you have the <sys/ndir.h> header file, and it defines `DIR'.
   */
/* #undef HAVE_SYS_NDIR_H */

/* Define to 1 if you have the <sys/stat.h> header file. */
#define HAVE_SYS_STAT_H 1

/* Define to 1 if you have the <sys/types.h> header file. */
#define HAVE_SYS_TYPES_H 1

/* Define to 1 if you have <sys/wait.h> that is POSIX.1 compatible. */
#define HAVE_SYS_WAIT_H 1

/* Define to 1 if you have the <unistd.h> header file. */
#define HAVE_UNISTD_H 1

/* Define to 1 if you have the `wait3' system call. Deprecated, you should no
   longer depend upon `wait3'. */
#define HAVE_WAIT3 1

/* Define to 1 if `major', `minor', and `makedev' are declared in <mkdev.h>.
   */
/* #undef MAJOR_IN_MKDEV */

/* Define to 1 if `major', `minor', and `makedev' are declared in
   <sysmacros.h>. */
/* #undef MAJOR_IN_SYSMACROS */

/* Name of package */
#define PACKAGE "cxterm"

/* Define to the address where bug reports for this package should be sent. */
#define PACKAGE_BUGREPORT ""

/* Define to the full name of this package. */
#define PACKAGE_NAME ""

/* Define to the full name and version of this package. */
#define PACKAGE_STRING ""

/* Define to the one symbol short name of this package. */
#define PACKAGE_TARNAME ""

/* Define to the version of this package. */
#define PACKAGE_VERSION ""

/* Define as the return type of signal handlers (`int' or `void'). */
#define RETSIGTYPE void

/* Define to 1 if the `setpgrp' function takes no argument. */
#define SETPGRP_VOID 1

/* Define to 1 if you have the ANSI C header files. */
#define STDC_HEADERS 1

/* Define to 1 if you can safely include both <sys/time.h> and <time.h>. */
#define TIME_WITH_SYS_TIME 1

/* Define to 1 if your <sys/time.h> declares `struct tm'. */
/* #undef TM_IN_SYS_TIME */

/* Version number of package */
#define VERSION "5.2"

/* Define to 1 if the X Window System is missing or not being used. */
/* #undef X_DISPLAY_MISSING */

/* Define to 1 if `lex' declares `yytext' as a `char *' by default, not a
   `char[]'. */
/* #undef YYTEXT_POINTER */

/* Define to `int' if <sys/types.h> does not define. */
/* #undef pid_t */
