       SHELL = /bin/sh
        MAKE = make
       XMKMF = xmkmf

all:
	@echo "Please use"
	@echo "		make World"
	@echo ""
	@echo "Do not name your log file make.log or it will be deleted."
	@echo "Make sure X11 binaries (such as xmkmf) are in PATH."
	@echo "If the top-level Makefile gets corrupted, copy Makefile.ini"
	@echo "to Makefile and try again."

World:
	@echo ""
	@echo "Building cxterm Version 5.2"
	@echo ""
	@date
	@echo ""
	@rm -f .done
	$(XMKMF)
	$(MAKE) $(MFLAGS) xrelease
	$(MAKE) $(MFLAGS) Makefiles
	$(MAKE) $(MFLAGS) includes
	$(MAKE) $(MFLAGS) $(WORLDOPTS)
	@touch .done
	@echo ""
	@date
	@echo ""
	@echo "Full build of cxterm complete."
	@echo ""

Makefile:
	$(XMKMF)
